# Generated by Django 4.2 on 2024-07-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='location_text_en',
            field=models.TextField(null=True, verbose_name='location_text'),
        ),
    ]
