# Generated by Django 4.2 on 2024-07-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_news_slug_alter_settings_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='banner',
            field=models.ImageField(null=True, upload_to='common/news/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
