# Generated by Django 4.2 on 2024-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_aboutapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutapp',
            name='caption_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutapp',
            name='caption_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutapp',
            name='caption_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutapp',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutapp',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutapp',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
