# Generated by Django 4.2 on 2024-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_aboutapp_caption_en_aboutapp_caption_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutapp',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
