# Generated by Django 4.2 on 2024-07-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_faq_options_faq_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
