# Generated by Django 4.2 on 2024-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_faq_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutapp',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
